import pytest
from django.core.exceptions import ValidationError

def something_test():
  pass
